# Generated by Django 5.2.6 on 2025-10-21 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_alter_comment_author_alter_like_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user1',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user2',
            new_name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'recipient')},
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('from_user', 'to_user')},
        ),
    ]
