# Generated by Django 5.2.6 on 2025-10-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birsth_date',
        ),
    ]
